### ISSUE TITLE
Build out contribution guide to the CNCF ecosystem

### ISSUE THREAD

**Issue by caniszczyk** [cncf/contribute#1]
We need a single place that outlines how to contribute to various parts of the CNCF ecosystem, including our projects, working groups and other areas.

**Comment by caniszczyk** [comment]
@idvoretskyi we will work on this and get it done in January

**Comment by InAnimaTe** [comment]
^glad this is getting done soon. I'd like to get much more involved but don't really know exactly where to start. Highlighting the areas that need attention would be immensely helpful.

**Comment by idvoretskyi** [comment]
Updated the README with per-project sections - https://github.com/cncf/contribute/pull/2.

**Comment by florianeichin** [comment]
This is a good approach as the single projects are very different in details. RKT for instance has kind of good development and contribution guidelines, while notary has more or less none.

**Comment by idvoretskyi** [comment]
Per-project guides added https://github.com/cncf/contribute/pull/3

**Comment by caniszczyk** [comment]
The initial cut is done and great, thanks all!
