### ISSUE TITLE
Add personas to contributors guide

### ISSUE THREAD

**Issue by caniszczyk** [cncf/contribute#24]
It would be good to add a Personas section or something to the guide for people to contribute based on their skills (docs,  designs, code etc)

See Fedora as a good example: https://fedoraproject.org/wiki/Join

**Comment by caniszczyk** [comment]
cc: @amye

**Comment by amye** [comment]
Fedora is a great example! 
Developers is an easy persona to create pathways for, Ambassadors is great for events planning, Technical Writers can be paired with some of the work that @lucperkins does - but I'm drawing a blank on a good pathway for Designers. @idvoretskyi, any good onboarding for designers that comes to mind?

**Comment by idvoretskyi** [comment]
> any good onboarding for designers that comes to mind?

@amye I'm not sure at the moment, so we may proceed without. Maybe @alexcontini may have some suggestions on this.

**Comment by amye** [comment]
Best to leave a placeholder for design and see what comes up.

**Comment by idvoretskyi** [comment]
+1

**Comment by caniszczyk** [comment]
we have maintainers: https://contribute.cncf.io/maintainers/ and contributors now: https://contribute.cncf.io/contributors/
