### ISSUE TITLE
contributors.cncf.io - create a web presence and not a GitHub repo? 

### ISSUE THREAD

**Issue by parispittman** [cncf/contribute#38]
cross posting from here: 
https://github.com/cncf/sig-contributor-strategy/issues/47

it would be good to have a community site focused on the people contributing and not point to a GitHub repo of docs (which this site can also house in a good, discoverable way)

maintainers.cncf.io is also being used to host the public maintainers list for TOC voting purposes but I can envision this as a page where maintainers of projects can grab information, form community, and have a one stop shop for everything that they need from the ecosystem.it can continue to host the public spreadsheet with a note about what it is, host the cncf/project-templates, all maintainers-circle information and maybe a curated events list.

this could be nested under cncf.io/people or cncf.io/community
what do folks think? other ideas?

highlight projects with contributor needs (looking for new contributors in a certain area, etc) - this can help end users with the ambiguous questions of where to contribute at scale 
bubble up cncf/contribute repo 
bubble up cncf/project-templates repo 
bubble up the maintainers list repo 
highlight upcoming events for contributors / maintainers
maintainer circle information/bubble up content in the contrib strat repo
highlights on contributors?/house contributor stories/profiles here
community terminology and explanations 
in memoriam page 
pictures!

**Comment by carolynvs** [comment]
Oh I like **contributors**.cncf.io and it's not taken. 👍

**Comment by awaiken** [comment]
excellent idea, and providing use cases for users is always helpful

**Comment by mrbobbytables** [comment]
I'm supportive of this idea. The repo was created here because it was fairly easy to maintain.

**Comment by iennae** [comment]
+1 to this being an excellent idea

**Comment by idvoretskyi** [comment]
Fixed with https://github.com/cncf/contribute/pull/43

**Comment by jberkus** [comment]
This is now ready to go thanks to the terrific work of @carolynvs , we just need to switch DNS.  As such, turning over to our TOC liaisons for final approval of the new site conceptually.

Do note that the site is still a WIP.  It is, however, considerably more polished than what is currently available at contribute.cncf.io, and as such is ready to go live (we believe).

Here's the netlify of the new site: cncf-contribute.netlify.app

@alena1108
@saad-ali

**Comment by saad-ali** [comment]
Looks great, thanks @jberkus and @carolynvs!

**Comment by idvoretskyi** [comment]
This is done (thanks @carolynvs!), available at http://contribute.cncf.io/.
