### ISSUE TITLE
Wrong Date on Last Modified

### ISSUE THREAD

**Issue by anujeet-chatterjee** [cncf/contribute#59]
## Problem:
I think the Last Modified Date has issues.

## Behaviour:
Observed: 
"Last modified January 1, 0001"

Expected:
"Last modified <b>\<<i>Valid Date</i>\></b>"

---
## Image References:

![image](https://user-images.githubusercontent.com/87376606/125467478-232c11e6-7402-4ce7-ada7-6cbb3d9b1b80.png)

**Comment by carolynvs** [comment]
Thanks for letting me know. Looks like a few pages are missing a timestamp. I'll get that fixed!
