### ISSUE TITLE
containerd project missing

### ISSUE THREAD

**Issue by abhi-bhatra** [cncf/contribute#64]
containerd project
Github Repo and Contributor Guide Links are broken or missing.
Link provided in the CNCF Page below, may no longer exist:

[Github Repo](https://github.com/containerd/containerd)
[Contributor Guide](https://github.com/containerd/containerd/blob/master/CONTRIBUTING.md)

<img width="500" alt="containerd" src="https://user-images.githubusercontent.com/63901956/126897928-738db193-3fbf-4ce5-8c6d-db8c71756a6d.png">

**Comment by camerondurham** [comment]
This might be resolved by #93?
