### ISSUE TITLE
Pull projects from landscape instead?

### ISSUE THREAD

**Issue by amye** [cncf/contribute#69]
One thing that we're starting to do across CNCF is using the landscape as the source of data.
Would it make sense do that here and then maybe add to it?

**Comment by carolynvs** [comment]
If we had two data sources, one from the landscape and another with custom info just for this repo, we could combine them during build and render the pages that way. That way, when we add new sandbox projects they would be added to this site as soon as you have the landscape updated.

**Comment by amye** [comment]
@cjyabraham: what are the bad ideas with this proposal. :D

**Comment by cjyabraham** [comment]
We wanted to avoid having any project metadata only on cncf.io so we appealed to the landscape people to include everything we wanted in the landscape.yml file, which they did.  It keeps it simpler for any updates to only have to happen in the landscape repo. 

We do, however, store a copy of the data in cncf.io for easy access.  We refresh the copy every 12 hours.  So far it has been working well.

**Comment by amye** [comment]
This is a little different, this site under /contribute lets projects submit things like language: https://contribute.cncf.io/contributors/, which would likely not be in the landscape.

**Comment by cjyabraham** [comment]
We actually do seem to have the languages in landscape:

<img width="352" alt="Screen Shot 2021-09-28 at 8 08 10 PM" src="https://user-images.githubusercontent.com/463160/135196456-f88a49c0-de04-4844-9a03-4c41736032ea.png">

**Comment by cjyabraham** [comment]
Also, FYI, we've basically done all this for the www.cncf.io site so the code used to access all the landscape data could be copied [from there](https://github.com/cncf/wp-mu-plugins/blob/main/lf-mu/admin/class-lf-mu-admin.php#L515).

**Comment by idvoretskyi** [comment]
A follow-up on this - is there anything in particular we can do @cjyabraham?

**Comment by cjyabraham** [comment]
Yes, this feature is doable but not sure who will do it.  So far I have not had anything to do with the contribute site.  If I'm to take it on perhaps a good time for it would be when we work on its theme early next year.  We have a new brand system for cncf in the works which will be extended for all subdomain sites like contribute.

**Comment by idvoretskyi** [comment]
We're not in rush, thanks @cjyabraham!

cc @carolynvs

**Comment by cjyabraham** [comment]
I am working on this as part of [this PR](https://github.com/cncf/tag-contributor-strategy/pull/187). Does anyone have an objection to me pulling in the content from this repo into the [tag-contributor-strategy](https://github.com/cncf/tag-contributor-strategy) repo? Once I automate all the project info, there is really not much extra content left so doesn't really make sense to keep it in this different repo. Additionally, automating the import and rebuild of the Contribute site is easier to do from one repo.

**Comment by carolynvs** [comment]
@cjyabraham Am I understanding right that this would let us consolidate all of the contribute.cncf.io content (maintainers + project info for contributors) into the cncf/tag-contributor-strategy repo and we wouldn't need to combine the two repos anymore to build the site? I really hope that's the plan because it would make me happy!

**Comment by cjyabraham** [comment]
Yes, exactly :)

Ok, I'll move forward with that solution.

**Comment by amye** [comment]
Hurray, I knew we could do it - I just didn't know if there was an intention behind having two separate.

**Comment by cjyabraham** [comment]
Here is [the new "Contributors" section](https://deploy-preview-187--cncf-contribute.netlify.app/contributors/) with data dynamically loaded from landscape. LMK if you have any comments.

**Comment by carolynvs** [comment]
*squee* This is looking so good, @cjyabraham!

**Comment by cjyabraham** [comment]
[Project data](https://contribute.cncf.io/contributors/) is now being automatically pulled in from landscape and [the Contribute repo](https://github.com/cncf/contribute) has been archived.
