### ISSUE TITLE
Projects List needs to be updated

### ISSUE THREAD

**Issue by Anubhavjoshi040** [cncf/contribute#70]
Projects list in [_index.md](https://github.com/cncf/contribute/blob/main/content/contributors/_index.md) needs some updates as the list does not contain all the projects and some graduated ones are still in the incubated projects list. Also need to add recently incubated projects to the list.

**Comment by amye** [comment]
Projects add themselves, I've added a note for this on the sandbox onboarding template.

**Comment by Anubhavjoshi040** [comment]
Still need to move projects like "etcd", "Open Policy Agent" from incubated to graduated, same in the case of "Cortex", "Thanos", "Flux", "KEDA" which are incubated and are listed in sandbox.

**Comment by idvoretskyi** [comment]
@Anubhavjoshi040 thanks for flagging!

It's a bit outdated, but you are welcome to submit a PR to fix this :)

**Comment by Anubhavjoshi040** [comment]
@idvoretskyi Sure!
